// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Common: typeof import('./src/components/common/CommonNavigation.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCollapse: typeof import('element-plus/es')['ElCollapse']
        ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}

export {}
