// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArchiveFile: typeof import('./src/components/homepage/ArchiveFile.vue')['default']
    Common: typeof import('./src/components/common/CommonNavigation.vue')['default']
    CommonNavigation: typeof import('./src/components/common/CommonNavigation.vue')['default']
    CourseCard: typeof import('./src/components/homepage/CourseCard.vue')['default']
    CourseNav: typeof import('./src/components/courseDetails/CourseNav.vue')['default']
    Editor: typeof import('./src/components/utils/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Homework: typeof import('./src/components/courseDetails/homework/Homework.vue')['default']
    Interact: typeof import('./src/components/courseDetails/interact/interact.vue')['default']
    Navigation: typeof import('./src/components/homepage/Navigation.vue')['default']
    PersonalDeliver: typeof import('./src/components/utils/PersonalDeliver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StuHomework: typeof import('./src/components/courseDetails/homework/StuHomework.vue')['default']
    TaskCommitNav: typeof import('./src/components/utils/TaskCommitNav.vue')['default']
    Topic: typeof import('./src/components/courseDetails/topic/Topic.vue')['default']
  }
}

export {}
