// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArchiveFile: typeof import('./src/components/homepage/ArchiveFile.vue')['default']
    CommonNavigation: typeof import('./src/components/common/CommonNavigation.vue')['default']
    CourseCard: typeof import('./src/components/homepage/CourseCard.vue')['default']
    CourseNav: typeof import('./src/components/courseDetails/CourseNav.vue')['default']
    Editor: typeof import('./src/components/utils/Editor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Homework: typeof import('./src/components/courseDetails/homework/Homework.vue')['default']
    Interact: typeof import('./src/components/courseDetails/interact/Interact.vue')['default']
    Navigation: typeof import('./src/components/homepage/Navigation.vue')['default']
    PersonalDeliver: typeof import('./src/components/utils/PersonalDeliver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StuHomework: typeof import('./src/components/courseDetails/homework/StuHomework.vue')['default']
    TaskCommitNav: typeof import('./src/components/utils/TaskCommitNav.vue')['default']
    Topic: typeof import('./src/components/courseDetails/topic/Topic.vue')['default']
  }
}

export {}
