import { createApp } from "vue";
import { createPinia } from "pinia";
import router from "./router";
import App from "./App.vue";
import "element-plus/dist/index.css";
import "xe-utils";
import VXETable from "vxe-table";
import "vxe-table/lib/style.css";
const app = createApp(App);
app.use(router);
app.use(createPinia());
app.use(VXETable);
app.mount("#app");
